[package]
name = "ghostkey_client"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18.1"
glib = "0.19.9"
gio = "0.19.8"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
