import { Button, VerticalBox, HorizontalBox, GroupBox, GridBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    GridLayout {
        padding: 5px;
        Row{ // 
            HorizontalBox {
                max-height: 30px;
                Button { text: "Button 1"; }
                Button { text: "Button 2"; }
                Button { text: "Button 3"; }
            }
        }
        Row{ // 
            HorizontalLayout {
                spacing: 10px;
                    VerticalLayout {
                        padding-top: 0px;
                        padding-bottom: 40px;
                        padding-left: 10px;
                        HorizontalLayout {
                            max-height: 20px;
                            Button { text: "Online"; }
                            Button { text: "Offline"; }
                        }
                        VerticalLayout {
                            VerticalBox {
                                min-width: 400px;
                                // Here there should be a list of boards that are currently clasified as online by the server

                            }
                        }
                    }
                    GridLayout {
                        VerticalLayout {
                        HorizontalLayout{
                            padding: 5px;
                            VerticalLayout {
                                Text { text: "Board"; }
                                Text { text: "Command"; }
                            }
                            VerticalLayout {
                                TextInput { width: 100px; }
                                TextInput { width: 100px; }
                            }
                        }
                        HorizontalLayout{ //
                            spacing: 10px;
                            Button { text: "clear"; max-height: 15px; max-width: 20px;}
                            Button { text: "Send Command";  width: 165px ;}
                        }
                    }
                }
            }
        }
    }
}
